apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
spec:
  replicas: 2
  selector:
    matchLabels:
      name: busybox-pod
  template:
    metadata:
      labels:
        name: busybox-pod
    spec:
      containers:
      - name: busybox-container
        image: busybox
        command:
        - sh
        - "-c"
        - echo Hello Kubernetes! && sleep 3600
        resources:
          limits:
            cpu: "100m"
            memory: "300Mi"
---

#kubectl create deployment httpd-frontend --replicas=3 --image=httpd:2.4-alpine